/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_zhongjihao_mp3codecandroid_wavcodec_WavCoderJni */

#ifndef _Included_com_example_zhongjihao_mp3codecandroid_wavcodec_WavCoderJni
#define _Included_com_example_zhongjihao_mp3codecandroid_wavcodec_WavCoderJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_zhongjihao_mp3codecandroid_wavcodec_WavCoderJni
 * Method:    createWavEncoder
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_com_example_zhongjihao_mp3codecandroid_wavcodec_WavCoderJni_createWavEncoder
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_example_zhongjihao_mp3codecandroid_wavcodec_WavCoderJni
 * Method:    initWavEncoder
 * Signature: (JIII)V
 */
JNIEXPORT void JNICALL Java_com_example_zhongjihao_mp3codecandroid_wavcodec_WavCoderJni_initWavEncoder
  (JNIEnv *, jclass, jlong, jint, jint, jint);

/*
 * Class:     com_example_zhongjihao_mp3codecandroid_wavcodec_WavCoderJni
 * Method:    writePcmData
 * Signature: (J[SI)V
 */
JNIEXPORT void JNICALL Java_com_example_zhongjihao_mp3codecandroid_wavcodec_WavCoderJni_writePcmData
  (JNIEnv *, jclass, jlong, jshortArray, jint);

/*
 * Class:     com_example_zhongjihao_mp3codecandroid_wavcodec_WavCoderJni
 * Method:    writeWavHeader
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_example_zhongjihao_mp3codecandroid_wavcodec_WavCoderJni_writeWavHeader
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_example_zhongjihao_mp3codecandroid_wavcodec_WavCoderJni
 * Method:    destroyWavEncoder
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_example_zhongjihao_mp3codecandroid_wavcodec_WavCoderJni_destroyWavEncoder
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
