/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_zhongjihao_mp3codecandroid_swig_SwigTest */

#ifndef _Included_com_example_zhongjihao_mp3codecandroid_swig_SwigTest
#define _Included_com_example_zhongjihao_mp3codecandroid_swig_SwigTest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_zhongjihao_mp3codecandroid_swig_SwigTest
 * Method:    SayHello
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_zhongjihao_mp3codecandroid_swig_SwigTest_SayHello
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
